# Generated by Django 3.2.9 on 2021-11-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('document', models.CharField(choices=[('CC', 'CÉDULA CIUDADANÍA'), ('TI', 'TARJETA IDENTIDAD'), ('RC', 'REGISTRO CIVIL'), ('OT', 'OTROS')], max_length=30, verbose_name='Document')),
                ('document_number', models.CharField(max_length=30, verbose_name='Document Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('address', models.CharField(max_length=30, verbose_name='Address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
